default_platform(:ios)

platform :ios do

  lane :beta do

    sync_code_signing(
      type: "appstore",
      readonly: false,
    )

    cocoapods
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })
  
    build_app(
      clean: false,
      workspace: "starter.xcworkspace",
      configuration: "Release",
      scheme: "starter",
      export_method: "app-store",
      output_directory: "./build"
    )

    changelog_from_git_commits

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )

    add_git_tag(
      grouping: "fastlane",
      prefix: "#{get_version_number}-build"
    )
    push_git_tags

  end

end
